[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://<your-render-backend-domain>/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


