name: Deploy Backend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "backend/**"
      - "vercel.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel env (optional)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy API to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
        run: |
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN --yes


